# Generated by Django 3.1.7 on 2021-04-16 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatKeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('user1_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_user', to='core.receivermodel')),
                ('user1_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_user', to='core.sendermodel')),
                ('user2_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receivermodel')),
                ('user2_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sendermodel')),
            ],
        ),
    ]
