# Generated by Django 3.1.7 on 2021-04-15 14:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receiver',
            new_name='ReceiverModel',
        ),
        migrations.RenameModel(
            old_name='Sender',
            new_name='SenderModel',
        ),
    ]
