# Generated by Django 3.1.7 on 2021-04-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatkeymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatkeymodel',
            name='user1_receiver',
        ),
        migrations.RemoveField(
            model_name='chatkeymodel',
            name='user1_sender',
        ),
        migrations.RemoveField(
            model_name='chatkeymodel',
            name='user2_receiver',
        ),
        migrations.RemoveField(
            model_name='chatkeymodel',
            name='user2_sender',
        ),
        migrations.AddField(
            model_name='chatkeymodel',
            name='usernames',
            field=models.JSONField(default=list),
        ),
    ]
